In [2]:
pip install jupyterlab-git

Collecting jupyterlab-git
  Downloading jupyterlab_git-0.53.0-py3-none-any.whl.metadata (3.7 kB)
Successfully installed fqdn-1.5.1 isoduration-20.11.0 jupyterlab-git-0.53.0 jupyterlab-git-core-0.53.0 nbdime-4.0.4 uri-template-1.3.0 webcolors-25.10.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
web_logs=pd.read_csv(r"dataset\web_analytics_logs_10k.csv")
web_logs.head()

   session_id  user_id session_date  traffic_source      utm_source utm_medium  \
0     S000001     1399   2024-12-15   Instagram Ads    Facebook Ads    organic

In [10]:
top5_Pages_viewed = web_logs.sort_values(by='pages_viewed', ascending=False).head(5)
print(top5_Pages_viewed)

      session_id  user_id session_date traffic_source    utm_source utm_medium  \
7412    S007413     2003   2024-11-10    YouTube Ads  LinkedIn Ads    organic

In [12]:
import pandas as pd
crm_conversion=pd.read_csv(r"dataset\crm_conversions_10k.csv")
crm_conversion.head()

  conversion_id  user_id   lead_date conversion_date lead_stage  \
0       C000001     2661  2025-11-05       2025-06-23        SQL

In [15]:
import pandas as pd
ad_spend=pd.read_csv(r"dataset\ad_spend_10k.csv")
ad_spend.head()

,spend_id,date,channel,campaign,utm_source,utm_medium,utm_campaign,impressions,clicks,ad_spend,country
0,1,2024-04-12,YouTube Ads,Campaign_XYZ,Organic Search,email,Product Launch,406926,10464,6840.21,UK
1,2,2025-03-11,Organic Search,Black Friday,Instagram Ads,social,Campaign_XYZ,462313,161,8577.80,Australia
2,3,2024-09-27,LinkedIn Ads,Brand Awareness,YouTube Ads,social,Brand Awareness,392386,3429,6765.49,Australia
3,4,2024-04-16,Google Ads,Campaign_XYZ,LinkedIn Ads,email,Retargeting,225300,3201,643.99,Germany
4,5,2024-03-12,LinkedIn Ads,NaN,YouTube Ads,organic,Festive Offer,301951,7695,3573.63,Germany

In [7]:
import pandas as pd

In [8]:
web_logs=pd.read_csv(r"dataset\web_analytics_logs_10k.csv")
web_logs.head()

In [9]:
crm_conversion=pd.read_csv(r"dataset\crm_conversions_10k.csv")
crm_conversion.head()

In [10]:
ad_spend=pd.read_csv(r"dataset\ad_spend_10k.csv")
ad_spend.head()

In [11]:
crm_conversion.isnull().sum()

In [3]:
import pandas as pd

In [4]:
web_logs=pd.read_csv(r"dataset\web_analytics_logs_10k.csv")
web_logs.head()

,session_id,user_id,session_date,traffic_source,utm_source,utm_medium,utm_campaign,device,city,country,pages_viewed,session_duration_sec,bounce_flag
0,S000001,1399,2024-12-15,Instagram Ads,Facebook Ads,organic,Festive Offer,Mobile,Delhi,Germany,15,3410,0
1,S000002,4352,2024-04-09,Organic Search,Organic Search,email,Brand Awareness,Desktop,Bangalore,Australia,18,1206,1
2,S000003,2935,2024-10-13,YouTube Ads,LinkedIn Ads,email,Retargeting,Desktop,Berlin,UK,4,3224,0
3,S000004,2272,2024-09-25,Google Ads,LinkedIn Ads,cpc,Summer Sale,Desktop,Bangalore,UK,10,2930,0
4,S000005,3390,2024-12-14,YouTube Ads,Google Ads,organic,Brand Awareness,Desktop,Mumbai,UK,2,1540,0

In [5]:
web_logs.isnull().sum()

session_id                0
user_id                   0
session_date              0
traffic_source            0
utm_source                0
utm_medium                0
utm_campaign            600
device                    0
city                    600
country                   0
pages_viewed              0
session_duration_sec      0
bounce_flag               0
dtype: int64

In [6]:
web_logs.isnull().mean() * 100

session_id              0.0
user_id                 0.0
session_date            0.0
traffic_source          0.0
utm_source              0.0
utm_medium              0.0
utm_campaign            6.0
device                  0.0
city                    6.0
country                 0.0
pages_viewed            0.0
session_duration_sec    0.0
bounce_flag             0.0
dtype: float64

In [7]:
web_logs['utm_campaign'] = web_logs['utm_campaign'].fillna('Unknown')

In [8]:
web_logs['city'] = web_logs['city'].fillna('Unknown')

In [9]:
web_logs.isnull().sum()

session_id              0
user_id                 0
session_date            0
traffic_source          0
utm_source              0
utm_medium              0
utm_campaign            0
device                  0
city                    0
country                 0
pages_viewed            0
session_duration_sec    0
bounce_flag             0
dtype: int64

In [10]:
web_logs.duplicated().sum()

np.int64(0)

In [12]:
web_logs = web_logs.drop_duplicates()

In [11]:
web_logs.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   session_id            10000 non-null  str
 1   user_id               10000 non-null  int64
 2   session_date          10000 non-null  str
 3   traffic_source        10000 non-null  str
 4   utm_source            10000 non-null  str
 5   utm_medium            10000 non-null  str
 6   utm_campaign          10000 non-null  str
 7   device                10000 non-null  str
 8   city                  10000 non-null  str
 9   country               10000 non-null  str
 10  pages_viewed          10000 non-null  int64
 11  session_duration_sec  10000 non-null  int64
 12  bounce_flag           10000 non-null  int64
dtypes: int64(4), str(9)
memory usage: 1015.8 KB

In [12]:
web_logs.describe()

            user_id  pages_viewed  session_duration_sec   bounce_flag
count  10000.000000  10000.000000           10000.00000  10000.000000
mean    2733.968400     12.534300            1818.31890      0.282800
std     1005.007399      6.904476            1032.57411      0.450383
min     1000.000000      1.000000              16.00000      0.000000
25%     1859.750000      7.000000             925.00000      0.000000
50%     2734.000000     13.000000            1827.00000      0.000000
75%     3593.000000     19.000000            2711.00000      1.000000
max     4499.000000     24.000000            3599.00000      1.000000

In [13]:
web_logs['traffic_source'].value_counts()

traffic_source
Google Ads        1484
YouTube Ads       1479
Organic Search    1457
Email             1433
Instagram Ads     1408
LinkedIn Ads      1371
Facebook Ads      1368
Name: count, dtype: int64

In [16]:
ad_spend.isnull().sum()

spend_id          0
date              0
channel           0
campaign        700
utm_source      700
utm_medium        0
utm_campaign      0
impressions       0
clicks            0
ad_spend          0
country           0
dtype: int64

In [17]:
ad_spend['campaign'] = ad_spend['campaign'].fillna('Unknown')

In [18]:
ad_spend['date'] = pd.to_datetime(ad_spend['date'])

In [19]:
ad_spend['ctr'] = ad_spend['clicks'] / ad_spend['impressions']

In [20]:
ad_spend['cpc'] = ad_spend['ad_spend'] / ad_spend['clicks']

In [21]:
ad_spend['campaign'] = ad_spend['campaign'].fillna('Unknown')
ad_spend['utm_source'] = ad_spend['utm_source'].fillna('Unknown')

In [22]:
ad_spend.isnull().sum()

spend_id        0
date            0
channel         0
campaign        0
utm_source      0
utm_medium      0
utm_campaign    0
impressions     0
clicks          0
ad_spend        0
country         0
ctr             0
cpc             0
dtype: int64

In [23]:
import pandas as pd
import os

In [24]:
BASE = r"dataset"
ad_spend = pd.read_csv(os.path.join(BASE, "ad_spend_10k.csv"))

In [25]:
ad_spend.groupby('channel')['ad_spend'].sum()

channel
Email             7038866.11
Facebook Ads      7320533.10
Google Ads        7356371.49
Instagram Ads     6884330.60
LinkedIn Ads      7387917.12
Organic Search    7548744.59
YouTube Ads       7369202.58
Name: ad_spend, dtype: float64

In [26]:
ad_spend.head()

,spend_id,date,channel,campaign,utm_source,utm_medium,utm_campaign,impressions,clicks,ad_spend,country
0,1,2024-04-12,YouTube Ads,Campaign_XYZ,Organic Search,email,Product Launch,406926,10464,6840.21,UK
1,2,2025-03-11,Organic Search,Black Friday,Instagram Ads,social,Campaign_XYZ,462313,161,8577.80,Australia
2,3,2024-09-27,LinkedIn Ads,Brand Awareness,YouTube Ads,social,Brand Awareness,392386,3429,6765.49,Australia
3,4,2024-04-16,Google Ads,Campaign_XYZ,LinkedIn Ads,email,Retargeting,225300,3201,643.99,Germany
4,5,2024-03-12,LinkedIn Ads,NaN,YouTube Ads,organic,Festive Offer,301951,7695,3573.63,Germany

In [27]:
import pandas as pd

ad_spend = pd.read_csv(
    "https://raw.githubusercontent.com/hitteshkharyal/Marketing-_ROI_Dashboard/main/dataset/ad_spend_10k.csv"
)

crm = pd.read_csv(
    "https://raw.githubusercontent.com/hitteshkharyal/Marketing-_ROI_Dashboard/main/dataset/crm_conversions_10k.csv"
)

web = pd.read_csv(
    "https://raw.githubusercontent.com/hitteshkharyal/Marketing-_ROI_Dashboard/main/dataset/web_analytics_logs_10k.csv"
)

print("Ad Spend Shape:", ad_spend.shape)
print("CRM Shape:", crm.shape)
print("Web Shape:", web.shape)

Ad Spend Shape: (10000, 11)
CRM Shape: (10000, 11)
Web Shape: (10000, 13)

In [22]:
print("Ad Spend Shape:", ad_spend.shape)
print("CRM Shape:", crm.shape)
print("Web Shape:", web.shape)

print("\nMissing Values")
print(ad_spend.isnull().sum())

Ad Spend Shape: (10000, 11)
CRM Shape: (10000, 11)
Web Shape: (10000, 13)

Missing Values
spend_id          0
date              0
channel           0
campaign        700
utm_source      700
utm_medium        0
utm_campaign      0
impressions       0
clicks            0
ad_spend          0
country           0
dtype: int64

In [28]:
ad_spend['campaign'] = ad_spend['campaign'].fillna('Unknown')
ad_spend['utm_source'] = ad_spend['utm_source'].fillna('Unknown')

In [29]:
print(ad_spend.isnull().sum())

spend_id        0
date            0
channel         0
campaign        0
utm_source      0
utm_medium      0
utm_campaign    0
impressions     0
clicks          0
ad_spend        0
country         0
dtype: int64

In [29]:
print("Ad Spend Duplicates:", ad_spend.duplicated().sum())
print("CRM Duplicates:", crm.duplicated().sum())
print("Web Duplicates:", web.duplicated().sum())

Ad Spend Duplicates: 0
CRM Duplicates: 0
Web Duplicates: 0

In [4]:
ad_spend.head()
crm.head()
web.head()

,session_id,user_id,session_date,traffic_source,utm_source,utm_medium,utm_campaign,device,city,country,pages_viewed,session_duration_sec,bounce_flag
0,S000001,1399,2024-12-15,Instagram Ads,Facebook Ads,organic,Festive Offer,Mobile,Delhi,Germany,15,3410,0
1,S000002,4352,2024-04-09,Organic Search,Organic Search,email,Brand Awareness,Desktop,Bangalore,Australia,18,1206,1
2,S000003,2935,2024-10-13,YouTube Ads,LinkedIn Ads,email,Retargeting,Desktop,Berlin,UK,4,3224,0
3,S000004,2272,2024-09-25,Google Ads,LinkedIn Ads,cpc,Summer Sale,Desktop,Bangalore,UK,10,2930,0
4,S000005,3390,2024-12-14,YouTube Ads,Google Ads,organic,Brand Awareness,Desktop,Mumbai,UK,2,1540,0

In [30]:
ad_spend.info()
crm.info()
web.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   spend_id      10000 non-null  int64
 1   date          10000 non-null  str
 2   channel       10000 non-null  str
 3   campaign      10000 non-null  str
 4   utm_source    10000 non-null  str
 5   utm_medium    10000 non-null  str
 6   utm_campaign  10000 non-null  str
 7   impressions   10000 non-null  int64
 8   clicks        10000 non-null  int64
 9   ad_spend      10000 non-null  float64
 10  country       10000 non-null  str
dtypes: float64(1), int64(3), str(7)
memory usage: 859.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   conversion_id      10000 non-null  str
 1   user_id            10000 non-null  int64
 2   lead_date          10000 non-null  str
 3   conversion_date    10000 non-null  str
 4   lead_stage         10000 non-null  str
 5   customer_journey   10000 non-null  str
 6   product            9200 non-null   str
 7   deal_value         10000 non-null  float64
 8   country            10000 non-null  str
 9   city               9200 non-null   str
 10  conversion_status  10000 non-null  str
dtypes: float64(1), int64(1), str(9)
memory usage: 859.5 KB
<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   session_id            10000 non-null  str
 1   user_id               10000 non-null  int64
 2   session_date          10000 non-null  str
 3   traffic_source        10000 non-null  str
 4   utm_source            10000 non-null  str
 5   utm_medium            10000 non-null  str
 6   utm_campaign          9400 non-null   str
 7   device                10000 non-null  str
 8   city                  9400 non-null   str
 9   country               10000 non-null  str
 10  pages_viewed          10000 non-null  int64
 11  session_duration_sec  10000 non-null  int64
 12  bounce_flag           10000 non-null  int64
dtypes: int64(4), str(9)
memory usage: 1015.8 KB

In [31]:
ad_spend["CTR"] = (
    ad_spend["clicks"] / ad_spend["impressions"]
) * 100

In [32]:
ad_spend["CPC"] = (
    ad_spend["ad_spend"] / ad_spend["clicks"]
)

In [33]:
print(ad_spend.columns.tolist())

['spend_id', 'date', 'channel', 'campaign', 'utm_source', 'utm_medium', 'utm_campaign', 'impressions', 'clicks', 'ad_spend', 'country', 'CTR', 'CPC']

In [34]:
ad_spend[['channel', 'CTR', 'CPC']].head()

          channel       CTR        CPC
0     YouTube Ads  2.571475   0.653690
1  Organic Search  0.034825  53.278261
2    LinkedIn Ads  0.873884   1.973021
3      Google Ads  1.420772   0.201184
4    LinkedIn Ads  2.548427   0.464409

In [35]:
import sqlite3
conn = sqlite3.connect("../marketing.db")

In [36]:
ad_spend.to_sql("ad_spend", conn, if_exists="replace", index=False)
web_logs.to_sql("web_logs", conn, if_exists="replace", index=False)
crm.to_sql("conversions", conn, if_exists="replace", index=False)

10000

In [40]:
pd.read_sql("SELECT * FROM web_logs LIMIT 5", conn)

,session_id,user_id,session_date,traffic_source,utm_source,utm_medium,utm_campaign,device,city,country,pages_viewed,session_duration_sec,bounce_flag
0,S000001,1399,2024-12-15,Instagram Ads,Facebook Ads,organic,Festive Offer,Mobile,Delhi,Germany,15,3410,0
1,S000002,4352,2024-04-09,Organic Search,Organic Search,email,Brand Awareness,Desktop,Bangalore,Australia,18,1206,1
2,S000003,2935,2024-10-13,YouTube Ads,LinkedIn Ads,email,Retargeting,Desktop,Berlin,UK,4,3224,0
3,S000004,2272,2024-09-25,Google Ads,LinkedIn Ads,cpc,Summer Sale,Desktop,Bangalore,UK,10,2930,0
4,S000005,3390,2024-12-14,YouTube Ads,Google Ads,organic,Brand Awareness,Desktop,Mumbai,UK,2,1540,0

In [50]:
pd.read_sql("SELECT * FROM ad_spend LIMIT 5", conn)

,spend_id,date,channel,campaign,utm_source,utm_medium,utm_campaign,impressions,clicks,ad_spend,country,CTR,CPC
0,1,2024-04-12,YouTube Ads,Campaign_XYZ,Organic Search,email,Product Launch,406926,10464,6840.21,UK,2.571475,0.653690
1,2,2025-03-11,Organic Search,Black Friday,Instagram Ads,social,Campaign_XYZ,462313,161,8577.80,Australia,0.034825,53.278261
2,3,2024-09-27,LinkedIn Ads,Brand Awareness,YouTube Ads,social,Brand Awareness,392386,3429,6765.49,Australia,0.873884,1.973021
3,4,2024-04-16,Google Ads,Campaign_XYZ,LinkedIn Ads,email,Retargeting,225300,3201,643.99,Germany,1.420772,0.201184
4,5,2024-03-12,LinkedIn Ads,Unknown,YouTube Ads,organic,Festive Offer,301951,7695,3573.63,Germany,2.548427,0.464409

In [44]:
pd.read_sql("SELECT * FROM conversions LIMIT 5", conn)

,conversion_id,user_id,lead_date,conversion_date,lead_stage,customer_journey,product,deal_value,country,city,conversion_status
0,C000001,2661,2025-11-05,2025-06-23,SQL,Facebook Ads > Website > Direct > Purchase,Enterprise Plan,7166.92,UK,Sydney,Won
1,C000002,3689,2024-12-07,2024-03-24,SQL,Google Ads > Website > Email > Purchase,Pro Plan,2033.82,Australia,Berlin,Won
2,C000003,2727,2025-10-13,2024-01-24,Won,Instagram Ads > Website > Email > Purchase,Analytics Suite,32142.83,Germany,Sydney,Won
3,C000004,2426,2025-08-26,2025-12-30,Lost,Google Ads > Website > Email > Purchase,Enterprise Plan,49837.98,Australia,London,Won
4,C000005,3755,2024-08-06,2025-03-24,Lost,YouTube Ads > Website > Direct > Purchase,Analytics Suite,29635.70,India,Berlin,Won

In [49]:
query = """
SELECT
    user_id,
    traffic_source,
    session_date,city,
    ROW_NUMBER() OVER (
        PARTITION BY user_id
        ORDER BY session_date
    ) AS step
FROM web_logs
"""
journey = pd.read_sql(query, conn)
journey.head(20)

    user_id  traffic_source session_date       city  step
0      1000    Facebook Ads   2025-01-02      Delhi     1
1      1000   Instagram Ads   2025-01-08     Mumbai     2
2      1000  Organic Search   2025-11-23      Delhi     3
3      1001      Google Ads   2024-01-09     Berlin     1
4      1001           Email   2024-05-26      Delhi     2
5      1001    LinkedIn Ads   2024-10-10      Delhi     3
6      1001    LinkedIn Ads   2025-10-05     Berlin     4
7      1001    LinkedIn Ads   2025-12-31  Bangalore     5
8      1002  Organic Search   2024-09-08    Unknown     1
9      1002     YouTube Ads   2024-10-03     Sydney     2
10     1003     YouTube Ads   2024-01-25      Delhi     1
11     1003    LinkedIn Ads   2024-02-19      Delhi     2
12     1003    Facebook Ads   2024-03-04     London     3
13     1003     YouTube Ads   2024-06-27  Bangalore     4
14     1003    LinkedIn Ads   2025-02-19   New York     5
15     1003   Instagram Ads   2025-10-04   New York     6
16     1004           Email   2024-10-29  Bangalore     1
17     1004  Organic Search   2025-06-13     Berlin     2
18     1005  Organic Search   2024-02-02   New York     1
19     1005           Email   2024-09-24     Sydney     2

In [53]:
import os
os.makedirs("../data/cleaned", exist_ok=True)
journey.to_csv("../data/cleaned/customer_journey.csv",index=False)

In [54]:
import os

print("Current Directory:", os.getcwd())
print("Files/Folders:", os.listdir())

Current Directory: C:\Users\bhara\OneDrive\Desktop\marketing_roi_dashboard\Marketing-_ROI_Dashboard
Files/Folders: ['.git', '.gitignore', '.ipynb_checkpoints', 'data', 'dataset', 'project1.ipynb', 'README.md']

In [57]:
journey[journey["user_id"] == 1000]

   user_id  traffic_source session_date    city  step
0     1000    Facebook Ads   2025-01-02   Delhi     1
1     1000   Instagram Ads   2025-01-08  Mumbai     2
2     1000  Organic Search   2025-11-23   Delhi     3

In [59]:
first_touch_query = """
SELECT
    user_id,
    traffic_source AS first_touch_channel
FROM (
    SELECT
        user_id,
        traffic_source,
        ROW_NUMBER() OVER (
            PARTITION BY user_id
            ORDER BY session_date) AS step
    FROM web_logs)
WHERE step = 1
"""
first_touch = pd.read_sql(first_touch_query, conn)
first_touch.head(20)

    user_id first_touch_channel
0      1000        Facebook Ads
1      1001          Google Ads
2      1002      Organic Search
3      1003         YouTube Ads
4      1004               Email
5      1005      Organic Search
6      1006        Facebook Ads
7      1007        Facebook Ads
8      1008        Facebook Ads
9      1009          Google Ads
10     1010               Email
11     1011       Instagram Ads
12     1012               Email
13     1013        Facebook Ads
14     1014       Instagram Ads
15     1016      Organic Search
16     1017        LinkedIn Ads
17     1018          Google Ads
18     1019       Instagram Ads
19     1020        LinkedIn Ads

In [60]:
first_touch_conv = first_touch.merge(
    crm,
    on="user_id",
    how="inner")
first_touch_conv.head()

,user_id,first_touch_channel,conversion_id,lead_date,conversion_date,lead_stage,customer_journey,product,deal_value,country,city,conversion_status
0,1000,Facebook Ads,C001962,2024-05-27,2025-02-26,Lost,Instagram Ads > Website > Email > Purchase,Pro Plan,18327.73,Australia,Berlin,Won
1,1000,Facebook Ads,C004837,2024-01-01,2024-09-06,Opportunity,Instagram Ads > Website > Email > Purchase,Enterprise Plan,16180.06,India,Berlin,Won
2,1000,Facebook Ads,C009984,2025-07-07,2024-04-16,Lead,YouTube Ads > Website > Direct > Purchase,Analytics Suite,26924.90,Australia,Berlin,Won
3,1001,Google Ads,C000886,2025-01-13,2025-08-05,Lost,LinkedIn Ads > Demo > Purchase,Marketing Suite,13793.37,India,Delhi,Lost
4,1002,Organic Search,C000590,2025-10-16,2025-09-18,Won,YouTube Ads > Website > Direct > Purchase,Pro Plan,32419.79,USA,New York,Lost

In [64]:
first_touch_conv.columns

Index(['user_id', 'first_touch_channel', 'conversion_id', 'lead_date',
       'conversion_date', 'lead_stage', 'customer_journey', 'product',
       'deal_value', 'country', 'city', 'conversion_status'],
      dtype='str')

In [67]:
query = """ select * from first_touch_conv"""
first_touch_conv

,user_id,first_touch_channel,conversion_id,lead_date,conversion_date,lead_stage,customer_journey,product,deal_value,country,city,conversion_status
0,1000,Facebook Ads,C001962,2024-05-27,2025-02-26,Lost,Instagram Ads > Website > Email > Purchase,Pro Plan,18327.73,Australia,Berlin,Won
1,1000,Facebook Ads,C004837,2024-01-01,2024-09-06,Opportunity,Instagram Ads > Website > Email > Purchase,Enterprise Plan,16180.06,India,Berlin,Won
2,1000,Facebook Ads,C009984,2025-07-07,2024-04-16,Lead,YouTube Ads > Website > Direct > Purchase,Analytics Suite,26924.90,Australia,Berlin,Won
3,1001,Google Ads,C000886,2025-01-13,2025-08-05,Lost,LinkedIn Ads > Demo > Purchase,Marketing Suite,13793.37,India,Delhi,Lost
4,1002,Organic Search,C000590,2025-10-16,2025-09-18,Won,YouTube Ads > Website > Direct > Purchase,Pro Plan,32419.79,USA,New York,Lost
...,...,...,...,...,...,...,...,...,...,...,...,...
9431,4498,Instagram Ads,C002634,2025-04-02,2024-10-04,Lead,LinkedIn Ads > Demo > Purchase,Basic Plan,45715.85,UK,London,Won
9432,4498,Instagram Ads,C002660,2024-05-31,2024-08-24,MQL,LinkedIn Ads > Demo > Purchase,Enterprise Plan,18151.12,Australia,Delhi,Won
9433,4498,Instagram Ads,C005502,2025-07-11,2025-09-03,Opportunity,YouTube Ads > Website > Direct > Purchase,Analytics Suite,9468.65,Germany,Delhi,Lost
9434,4499,Facebook Ads,C002259,2025-08-14,2024-11-10,Won,LinkedIn Ads > Demo > Purchase,Analytics Suite,11759.09,Germany,Bangalore,Lost
9435,4499,Facebook Ads,C005448,2025-03-09,2025-12-19,SQL,YouTube Ads > Website > Direct > Purchase,Basic Plan,30499.75,USA,London,Lost

In [68]:
first_touch_conv.groupby(
    "first_touch_channel"
)["deal_value"].sum().sort_values(ascending=False)

first_touch_channel
Instagram Ads     36285027.55
Email             35798132.76
YouTube Ads       34731950.44
Google Ads        34171505.17
Organic Search    33076151.85
Facebook Ads      31862296.11
LinkedIn Ads      30555981.61
Name: deal_value, dtype: float64

In [71]:
first_touch_conv.to_csv(
    "first_touch_attribution.csv",
    index=False)
first_touch=pd.read_csv("first_touch_attribution.csv")
first_touch.groupby(
    "first_touch_channel"
)["deal_value"].sum().sort_values(ascending=False)

first_touch_channel
Instagram Ads     36285027.55
Email             35798132.76
YouTube Ads       34731950.44
Google Ads        34171505.17
Organic Search    33076151.85
Facebook Ads      31862296.11
LinkedIn Ads      30555981.61
Name: deal_value, dtype: float64